# Generated by Django 4.2.3 on 2024-01-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='mostrar_en_pagina_dinamica',
            field=models.BooleanField(default=False),
        ),
    ]
