# Generated by Django 4.0.6 on 2024-01-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_correoenviado'),
    ]

    operations = [
        migrations.AddField(
            model_name='correoenviado',
            name='titulo',
            field=models.CharField(default='Correo Enviado', max_length=255),
        ),
    ]
